### ISSUE TITLE
Ensure support for all Fennec variants

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fennec-profile-manager#14]
Sebastian: "We are now confident to migrate beta and nightly too. So it would be great if we can create build variants that work with beta/nightly".

For FPM this would mean different build configurations with different `packageId`s and different `sharedUserId`s.
As `sharedUserId` Fennec Release and Beta use the same `org.mozilla.firefox.sharedID`
While Fennec Nightly uses `org.mozilla.fennec.sharedID`.

**Comment by vmbaicu** [comment]
fixed by https://github.com/mozilla-mobile/fennec-profile-manager/pull/19
