### ISSUE TITLE
[Bug] New backup can be created when permission to access storage is denied

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fennec-profile-manager#26]
## Preconditions:
Have Fennec and Firefox Profile Manager installed.
## Steps to reproduce
1. Launch Firefox Profile Manager with a fresh install or after clear data;
2. Tap Deny on permission storage;
3. Tap the Create button. 
### Expected behavior
The Create button is not working.
### Actual behavior
The Create button can be tapped and a new backup can be created.
### Notes:
The create button is not actionable all the time.
### Device information

* Android device: Samsung Galaxy S8 (Android 9); Pixel (Android Q); Motorola Nexus 6 (Android 7.1.1)
* Build Firefox Profile Manager v1.0 for Fennec Release, Beta and Nightly.

**Comment by vmbaicu** [comment]
fixed by https://github.com/mozilla-mobile/fennec-profile-manager/pull/30

**Comment by ebalazs-sv** [comment]
Hi! Verified as fixed on the second FPM build received with Samsung Galaxy S8 (Android 9); Motorola Nexus 6 (Android 7.1.1).
