### ISSUE TITLE
App unresponsive if the device orientation is changed & permissions denied

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fennec-profile-manager#27]
## Preconditions
Firefox Profile Manager is installed.

## Steps to reproduce
1. Open FPM. 
2. Deny permissions.
3. Switch the device orientation from portrait to landscape.

### Expected behavior
The app is displayed in landscape mode correctly. 

### Actual behavior
A blank screen is displayed and the app is unresponsive.

### Device information
* Android device: Google Pixel (Android Q); Samsung Galaxy S8 (Android 9).
* Build Firefox Profile Manager v1.0 for Fennec Release, Beta and Nightly.

**Comment by vmbaicu** [comment]
fixed by https://github.com/mozilla-mobile/fennec-profile-manager/pull/30
