### ISSUE TITLE
[Bug] Set backup name pop-up is dismissed when rotating the device

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fennec-profile-manager#29]
## Preconditions:
Have Fennec and Firefox Profile Manager installed.
## Steps to reproduce
1. Launch Firefox Profile Manager with a fresh install or after clear data;
2. Tap the Create button;
3. With the Set backup name pop-up displayed, rotate the device in landscape mode;
4. Observe the behavior.
### Expected behavior
The Set backup name pop-up is displayed.
### Actual behavior
The Set backup name pop-up is dismissed.
### Notes:
This is also reproducible for the Edit backup name, Apply pop-ups.
### Device information

* Android device: Samsung Galaxy S8 (Android 9); Pixel (Android Q); Motorola Nexus 6 (Android 7.1.1)
* Build Firefox Profile Manager v1.0 for Fennec Release, Beta and Nightly.

**Comment by vmbaicu** [comment]
we should constrain the app to work in portrait only , there is no need to have it work in landscape as well - fixed by https://github.com/mozilla-mobile/fennec-profile-manager/pull/30
