### ISSUE TITLE
Add confirmation step for "Delete" button

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fennec-profile-manager#31]
## Preconditions
- Firefox Profile Manager is installed.
- Backup1 is created. 

## Steps to reproduce
1. Open FPM. 
2. Swipe from left to right for Backup1.
3. Tap on the "Delete" button.

### Expected behavior
"Yes" and "Cancel" options are displayed. 
Note that for Apply, Edit, the options are displayed and we consider that "Delete" is important also. 

### Actual behavior
No confirmation step is displayed. 

### Device information
* Android device: Google Pixel (Android Q); Samsung Galaxy S8 (Android 9), Samsung Galaxy Tab A 6 (Android 5.1.1).l
* Build Firefox Profile Manager v1.0 for Fennec Release, Beta and Nightly.

**Comment by ebalazs-sv** [comment]
Verified as fixed on FPM v1.0 Build 2 Samsung Galaxy S8 (Android 9); Pixel (Android Q); Huawei Honor 8 (Android 7.0).
