### ISSUE TITLE
Backup not applied back on Fennec

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fennec-profile-manager#33]
## Preconditions
- Firefox Profile Manager is installed.

## Steps to reproduce
1. Open FPM. 
2. Create a backup for Fennec Nightly.
3. On Fennec go to Settings -> General -> Hide topsites and close Fennec.
4. Open FPM and apply the backup created at step 2.
5. Open Fennec again. 

### Expected behavior
The backup is applied and topsites are not hidden. 

### Actual behavior
The backup is not applied and the topsites are not displayed. 

### Device information
* Android device: Google Pixel (Android Q).
* Build Firefox Profile Manager v1.0 for Fennec Release, Beta and Nightly.

**Comment by ebalazs-sv** [comment]
Hi! I can reproduce this with Samsung Galaxy S8 (Android 9); Motorola Nexus 6 (Android 7.1.1) on build Firefox Profile Manager v1.0 for Fennec Release, Beta and Nightly.

**Comment by sflorean** [comment]
Logcat- ([Apply Issue - Android Q.txt](https://github.com/mozilla-mobile/fennec-profile-manager/files/3931666/Apply.Issue.-.Android.Q.txt))

**Comment by vmbaicu** [comment]
One of the requirements for applying a backup is that you have to have fennec closed. With the recent changes, we're attempting to kill Fennec's background process before applying

**Comment by ebalazs-sv** [comment]
Verified as fixed on FPM v1.0 Build 2  for Fennec Release, Beta and Nightly with Samsung Galaxy S8 (Android 9); Pixel (Android Q); Huawei Honor 8 (Android 7.0).
