### ISSUE TITLE
Visual issues when adding long name for backup

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fennec-profile-manager#34]
## Preconditions
- Firefox Profile Manager is installed.

## Steps to reproduce
1. Open FPM and tap on "+".
2. Add a long name (>50 characters).
3. Tap on "OK".

### Expected behavior
The name of the backup is displayed with no issues, the date of creation is displayed. 

### Actual behavior
![Screenshot_20191206-150857](https://user-images.githubusercontent.com/58466444/70325483-c0cc3680-183a-11ea-8bd6-619d8776b28a.png)

### Device information
* Android device: Google Pixel (Android Q).
* Build Firefox Profile Manager v1.0 for Fennec Release, Beta and Nightly.

**Comment by vmbaicu** [comment]
Should be fixed as of the latest merges.

**Comment by ebalazs-sv** [comment]
Verified as fixed on FPM v1.0 Build 2 Samsung Galaxy S8 (Android 9); Pixel (Android Q); Huawei Honor 8 (Android 7.0).
