### ISSUE TITLE
FPM crashes when applying an imported and new backups file

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fennec-profile-manager#42]
## Preconditions:
Have Fennec and Firefox Profile Manager installed.
## Steps to reproduce
1. Launch Firefox Profile Manager;
2. Tap the Import button;
3. Select any file available;
4. Go to the imported backup and select Apply;
### Expected behavior
Only the Fennec apk's can be selected with Import.
### Actual behavior
Any available file can be imported and when the Apply button is tapped, the app crahes.
### Notes:

[crash.txt](https://github.com/mozilla-mobile/fennec-profile-manager/files/3954416/crash.txt)

### Device information
* Android device: Samsung Galaxy S8 (Android 9); Pixel (Android Q); Huawei Honor 8 (Android 7.0)
* Build Firefox Profile Manager v1.0 Build 2 for Fennec Release, Beta and Nightly.

**Comment by Mugurell** [comment]
We are already filtering for only zip files.
The issue though is that the user can select *any* zip file.

To mitigate this I propose "signing" FPM produced zips with some custom block of bytes as the first in the encrypted zip.
Then when the user tries to import *any* zip we can first read the first block of bytes, check if it's what we expect and either proceed with trying to decrypt further or abort and present a message to the user that the zip is incompatible.

We can even go as far as using the Fennec package name as the "signature" and then have a way of informing the users that an incompatible zip either
- is not recognized by FPM (first block of bytes is not a fennec package name) and the import will be aborted
- is recognized but is for another fennec channel (release / beta / nightly) and we can offer users the option to continue with importing that or aborting.
In the case the zip seems to be for the right fennec channel we continue with the current behaviour - only show a message at the end if importing was not possible. 

Curious about your thoughts @Sparky93 @vmbaicu @ebalazs-sv.

**Comment by Mugurell** [comment]
We are already filtering for only zip files.
The issue though is that the user can select *any* zip file.

To mitigate this I propose "signing" FPM produced zips with some custom block of bytes as the first in the encrypted zip.
Then when the user tries to import *any* zip we can first read the first block of bytes, check if it's what we expect and either proceed with trying to decrypt further or abort and present a message to the user that the zip is incompatible.

We can even go as far as using the Fennec package name as the "signature" and then have a way of informing the users that an incompatible zip either
- is not recognized by FPM (first block of bytes is not a fennec package name) and the import will be aborted
- is recognized but is for another fennec channel (release / beta / nightly) and we can offer users the option to continue with importing that or aborting.

In the case the zip seems to be for the right fennec channel we continue with the current behaviour - only show a message at the end if importing was not possible. 

Curious about your thoughts @Sparky93 @vmbaicu @ebalazs-sv.

**Comment by sflorean** [comment]
This is still reproducible on newer FPM builds:
- if we **import an old backup** and perform the "apply" functionality: 
[ImportApplyCrash.txt](https://github.com/mozilla-mobile/fennec-profile-manager/files/3987812/ImportApplyCrash.txt)
- if we create a **new backup** and perform the "apply" functionality: 
[NewApplyCrash.txt](https://github.com/mozilla-mobile/fennec-profile-manager/files/3987820/NewApplyCrash.txt)

Device information
- Android device: Huawei Honor 8 (Android 7.0), Motorola Moto G6 (Android 8.0).
- Build Firefox Profile Manager v1.0 Build 3 for Fennec Release, Beta and Nightly.
**Note**: not reproducible on Samsung Galaxy S8 (Android 9).

**Comment by ebalazs-sv** [comment]
Verified as fixed on build Firefox Profile Manager v1.0 Build 4 for Fennec Release, Beta and Nightly with  Samsung Galaxy S8 (Android 9), Huawei Honor 8 (Android 7.0), Motorola Moto G6 (Android 8.0).
