### ISSUE TITLE
Throbber icon from creating/apply a backup is freezing

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fennec-profile-manager#44]
#### Preconditions:
Have Firefox Profile Manager installed.

#### Steps to reproduce
1. Launch Firefox Profile Manager;
2. Tap on the "+" button to create a new backup;
3. Set a name and tap on "OK";

#### Expected behavior
A Throbber is presented on the screen notifying the user that the new backup is creating.

#### Actual behavior
The Throbber is freezing.

#### Notes:
- This issue is reproducing also when you apply a backup;
- This issue is not reproducible on  Huawei Honor 8 (Android 7.0) and Samsung Galaxy Tab A6 (Android 5.1);
![20191212_113338](https://user-images.githubusercontent.com/40264165/70700455-7122ba80-1cd3-11ea-869c-daa4b169112b.gif)

#### Device information
Android device: Samsung Galaxy S8 (Android 9); Google Pixel (Android Q).
Build Firefox Profile Manager v1.0 Build 2 for Fennec Release, Beta and Nightly.

**Comment by ebalazs-sv** [comment]
This is still reproducible on Firefox Profile Manager v1.0 Build 3 for Fennec Release, Beta and Nightly with Samsung Galaxy S8 (Android 9).

**Comment by ebalazs-sv** [comment]
This is still reproducible on Firefox Profile Manager v1.0 Build 4 for Fennec Release, Beta and Nightly with Samsung Galaxy S8 (Android 9).

**Comment by Mugurell** [comment]
This really shouldn't happen.
Tried to reproduce but I couldn't.
Will investigate more.

**Comment by Mugurell** [comment]
After investigating this more this seems to be the expected result as confirmed with QA that this only reproduces if 
- power saving is on or 
- Developer settings -> Animator duration scale -> Animation off

these being the cases when all animations should be disabled (https://developer.android.com/reference/android/animation/ValueAnimator#areAnimatorsEnabled())
