### ISSUE TITLE
[regression] The permission storage pop-up is not displayed

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fennec-profile-manager#55]
## Preconditions:
Have Fennec and Firefox Profile Manager installed.
Have Permission storage disabled in FPM Android settings.
## Steps to reproduce
1. Launch Firefox Profile Manager;
2. Observe the behavior.
### Expected behavior
The permission storage pop-up is displayed with the Deny/Allow options.
### Actual behavior
The permission storage pop-up is not displayed.
### Notes:
This is also reproducible for fresh install or clear data.
### Device information
* Android device: Samsung Galaxy S8 (Android 9); Huawei Honor 8 (Android 7.0), Motorola Moto G6 (Android 8.0).
* Build Firefox Profile Manager v1.0 Build 3 for Fennec Release, Beta and Nightly.

**Comment by andlzr** [comment]
Production build variants uses internal storage (this does not require read/write permissions) and Development build variants uses external storage (this requires read/write permissions).
I'm closing this issue.
