### ISSUE TITLE
The imported backups are blank

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fennec-profile-manager#60]
## Steps to reproduce
1. Launch Firefox Profile Manager;
2. Tap the Import button;
3. Select a .fpm file;
4. Observe the UI for the imported backup; 
### Expected behavior
The imported backup is displayed.
### Actual behavior
The imported backups is blank.
### Notes:
[Screenshot](https://drive.google.com/file/d/1TaVlLfacVcihlL64TqKaVDNU8Gpmi_ng/view)
After restarting the app, the backups are displayed.
### Device information
* Android device: Samsung Galaxy S8 (Android 9); Huawei Honor 8 (Android 7.0), Motorola Moto G6 (Android 8.0).
* Build Firefox Profile Manager v1.0 Build 4 for Fennec Release, Beta and Nightly.

**Comment by Mugurell** [comment]
I think this is a consequence of #65 and as such should not be happen anymore after that ticket is fixed.
Please test again on a build containing the patches for #65

**Comment by ebalazs-sv** [comment]
Verified as fixed on FPM builds 6 with Samsung Galaxy S8 (Android 9), Motorola Moto G6 (Android 8.0), Google Pixel 3 (Android Q), Samsung Galaxy Tab A 6 (Android 5.1.1), HTC Desire 820 (Android 6.0.1), Huawei Honor 8 (Android 7.0).
I will close this issue. Thanks!
