### ISSUE TITLE
[FPM] Space between characters can be added when editing backup names. 

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fennec-profile-manager#61]
## Preconditions
- Firefox Profile Manager is installed.
- "test" is saved.

## Steps to reproduce
1. Open FPM and swipe from left to right for the backup displayed.
2. Choose "Edit".
3. Change from "test" to "test 1".

### Expected behavior
Space between characters can't be added. It should give an error or when is done editing, "test_1" should be displayed.

### Actual behavior
Space between characters can be added. 

### Device information
* Android device: Samsung Galaxy Tab A 6(Android 5.1.1), Samsung Galaxy S8 (Android 9); Huawei Honor 8 (Android 7.0), Motorola Moto G6 (Android 8.0).
* Build Firefox Profile Manager v1.0 for Fennec Release, Beta and Nightly.

**Comment by Mugurell** [comment]
After discussing in the team together with our QA colleagues we've went with allowing spaces in the names of the backups. We feel like this allows for more natural backup names, more informative.
Please check in the next build that all backup operations work as expected with backups containing spaces in their names.

**Comment by sflorean** [comment]
Verified as fixed on FPM build 7, space can be added in the name of the backup.
Devices:
- Google Pixel 3 (Android Q),
- Samsung Galaxy S8 (Android 9),
- Motorola Moto G6 (Android 8.0),
- Huawei Honor 8 (Android 7.0),
- HTC Desire 820 (Android 6.0.1),
- Samsung Galaxy Tab A 6 (Android 5.1.1).
