### ISSUE TITLE
[Regression] Crash when apply backup on certain devices

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fennec-profile-manager#71]
## Preconditions
- Firefox Profile Manager is installed.
- Firefox is installed. 

## Steps to reproduce
1. Open FPM and create a new backup.
2. Go to Firefox and change the settings -> close the browser.
3. Go to FPM and swipe from left to right for the backup added at step 1.
4. Tap on "Apply". 

### Expected behavior
The backup is applied. 

### Actual behavior
The FPM crashes. 

Logcat1:
2020-01-27 11:01:50.699 24286-24286/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fpm, PID: 24286
    java.io.FileNotFoundException: /data/user/0/org.mozilla.firefox/lib/libplugin-container.so (Permission denied)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
        at org.mozilla.fpm.utils.ZipUtils.extract(ZipUtils.java:92)
        at org.mozilla.fpm.data.BackupRepositoryImpl.deploy(BackupRepositoryImpl.kt:124)
        at org.mozilla.fpm.presentation.mvp.MainPresenter$applyBackup$1$1.invokeSuspend(MainPresenter.kt:45)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)

Logcat2:
[BetaCrashApply.txt](https://github.com/mozilla-mobile/fennec-profile-manager/files/4116273/BetaCrashApply.txt)

### Note
On devices with android >5, the backup is duplicated with "-temp" extension added to the name.

### Device information
* Android device: Huawei Honor 8 (Android 7.0), Sony Xperia Z5 Premium (Android 7.1.1), Nokia 6 (Android 7.1.1), Motorola Moto G6 (Android 8).
* Build Firefox Profile Manager v1.0 for Fennec Release, Beta and Nightly.

**Comment by Mugurell** [comment]
This one is interesting..
Applying a backup means writing all the files from a `.fpm` in Fennec's internal storage
For this we first are to delete all said internal storage files
Using `java.io.File.delete`, recursive calls done [here](https://github.com/mozilla-mobile/fennec-profile-manager/blob/1fa689e834fa239d091b92322aaec46836e754f8/app/src/main/java/org/mozilla/fpm/data/BackupRepositoryImpl.kt#L110). Calls that for whatever reason fail on some devices.
Then when we are trying to copy the new files [this call](https://github.com/mozilla-mobile/fennec-profile-manager/blob/1fa689e834fa239d091b92322aaec46836e754f8/app/src/main/java/org/mozilla/fpm/utils/ZipUtils.java#L92) throws.
After further investigations I found that our "lib" directory seems to be a symlink. For which we might indeed not have the right permissions. :-?
<img width="709" alt="Screenshot 2020-01-27 at 18 34 29" src="https://user-images.githubusercontent.com/11428869/73195417-7ed2b900-4136-11ea-8bb5-8b9a6090a221.png">

**Comment by sflorean** [comment]
ref https://github.com/mozilla-mobile/fennec-profile-manager/issues/42

**Comment by Mugurell** [comment]
Waiting for a confirmation from QA that all looks good now.
Based on the stacktrace and my investigation this is beyond strange so most I could do is just ignore such an exception if
- the needed file exists
- is not empty
- we can't write to it
All of the above should ensure that the file "should" be what the app needs and if based on the stracktrace and my findings this issue would only happen with app libs I think it's ok to ignore this issue in such cases.
Otherwise the app would still crash giving us the possibility to investigate more the crash cause.

**Comment by sflorean** [comment]
Verified as fixed on FPM build 7, "apply" works as expected.
Devices:
- Motorola Moto G6 (Android 8.0),
- Huawei Honor 8 (Android 7.0),
- HTC Desire 820 (Android 6.0.1),
- Samsung Galaxy Tab A 6 (Android 5.1.1).
