### ISSUE TITLE
Only the last backup is displayed if we add/import/edit multiple backups with the same name

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fennec-profile-manager#72]
## Preconditions
- Firefox Profile Manager is installed.
- Firefox is installed. 

## Steps to reproduce
1. Open FPM and create a backup "First run".
2. Go to Firefox and change the settings -> close the browser.
3. Open FPM again and create a backup "First run".
4. Close FPM.
5. Open FPM and pay attention to the backups created at step 1 and 3.

### Expected behavior
A message should inform the user that the first backup will be replaced by the new one, with options to continue or cancel.

### Actual behavior
Only the last backup is displayed, even if the browser settings were different (also the details: the size of the backup).

### Note
This is also reproducible for the import/edit option after the app is closed and opened. 

### Device information
* Android device: 
- Huawei Honor 8 (Android 7.0), 
- Motorola Moto G6 (Android 8.0)
- Google Pixel 3 (Android Q)
- Samsung S8 (Android 9.0)
- HTC Desire 820 (Android 6.0.1)

* Build Firefox Profile Manager v1.0 for Fennec Release, Beta and Nightly.

**Comment by ebalazs-sv** [comment]
This is also reproducible with the following scenario:
1. Import the same backup twice;
2. Delete one of the backups;
3. Close and reopen the app;
4. Observe the remaining backup;

Expected result:
The remaining backup is displayed after opening the app. 

Actual result:
The second backup is deleted.

**Comment by sflorean** [comment]
Verified as fixed on FPM build 7, each backup has a unique name when editing/importing/saving.
Devices:
- Google Pixel 3 (Android Q),
- Samsung Galaxy S8 (Android 9),
- Motorola Moto G6 (Android 8.0),
- Huawei Honor 8 (Android 7.0),
- HTC Desire 820 (Android 6.0.1),
- Samsung Galaxy Tab A 6 (Android 5.1.1).
