### ISSUE TITLE
The imported backups size are not aligned with the existing ones

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fennec-profile-manager#75]
### Precondition
Have backups created on FPM.
## Steps to reproduce
1. Launch Firefox Profile Manager;
2. Tap the Import button;
3. Select a .fpm file from a different version of Fennec;
4. Observe the UI for the imported backup; 
### Expected behavior
The imported backup size is aligned with the existing backup size.
### Actual behavior
The imported backups size are not aligned with the existing ones.
### Notes:
[Screenshot](https://drive.google.com/file/d/1-ST2JNz7jH6yrgOH4DXvMHjnMegrr0UW/view?usp=sharing)

### Device information
* Android device: Samsung Galaxy S8 (Android 9); Huawei Honor 8 (Android 7.0), Motorola Moto G6 (Android 8.0), Pixel 3 (Android Q);
* Build Firefox Profile Manager v1.0 Build 6 for Fennec Release, Beta and Nightly.

**Comment by Mugurell** [comment]
Waiting for a confirmation from QA that all looks good now.
The backup size should have the same text as before
Is just that now it will always be placed dead center horizontally

**Comment by ebalazs-sv** [comment]
Verified as fixed on FPM build 7 with the following devices:
- Google Pixel 3 (Android Q),
- Samsung Galaxy S8 (Android 9), 
- Motorola Moto G6 (Android 8.0), 
- Huawei Honor 8 (Android 7.0),
- HTC Desire 820 (Android 6.0.1),
- Samsung Galaxy Tab A 6 (Android 5.1.1). 
I will close this issue. Thanks!
